production:
  adapter: postgresql
  database: proposals
  pool: 5
  timeout: 5000

development:
  adapter: sqlite3
  database: db/proposals_dev.sqlite3

test:
  adapter: sqlite3
  database: db/proposals_test.sqlite3